import { AuthGuard } from "@/app/components/auth/AuthGuard";

import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "ログイン確認サンプルページ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthGuard>
      <section>{children}</section>
    </AuthGuard>
  );
}
