name: App CI

on:
  pull_request:
    branches: [main]
    paths:
      - "app/**"
  workflow_call: # app-deploy.yaml から呼び出し可能

jobs:
  ci:
    name: Lint & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: "./app/package.json"
          cache: "npm"
          cache-dependency-path: "./app/package-lock.json"

      - name: Install dependencies
        working-directory: ./app
        run: npm ci

      - name: Run Lint
        working-directory: ./app
        run: npm run lint

      - name: Run Test
        working-directory: ./app
        run: npm test
